### ISSUE TITLE
Apple Silicon / M1 Mac issues

### ISSUE THREAD

**Issue by mbirth** [ihaveamac/ninfs#73]
I'm trying to get ninfs to work on a Late-2020 MacBook Pro with Apple's new M1 chip. I've got an ARM-native Python 3.9.1 installed via homebrew, pulled in the requirements via pip3, created a wheel from latest ninfs source and installed that wheel - but running `mount_nandhac` crashes:

```
mbirth ~/D/ninfs> mount_nandhac --keys prod.keys -o allow_other /dev/disk4 fuse
WARNING: /opt/homebrew/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python is loading libcrypto in an unsafe way
fish: “mount_nandhac --keys prod_Thia.…” terminated by signal SIGABRT (Abort)
```

Don't know if the SIGABRT is a result of the libcrypto not loading "safely", or if those problems are unrelated and it crashes because of something else.

**Comment by ihaveamac** [comment]
I'm guessing that this is due to haccrypto including a copy of libcrypto for macOS which only supports Intel. Until it's updated, you can try replacing it with one with an arm64 slice. Copy the file from `/Library/Frameworks/Python.framework/Versions/3.9/lib/libcrypto.1.1.dylib` and put it to where haccrypto was installed:
* If you didn't use a venv or --user then it's likely at `/opt/homebrew/Cellar/python@3.9/3.9.1/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/haccrypto` (not too sure about this one as I don't use python from homebrew, let alone on an M1 device)
* If you did use --user then it's likely at `~/Library/Python/3.9/lib/python/site-packages/haccrypto`

After that try again. If it doesn't work, try another mount type (e.g. mount_3dsx with [FBI.3dsx](https://github.com/Steveice10/FBI/releases/download/2.6.0/FBI.3dsx))

**Comment by mbirth** [comment]
Thanks for the hint! With `openssl` installed via `brew`, the file was in `/opt/homebrew/Cellar/openssl@1.1/1.1.1i/lib/libcrypto.1.1.dylib`. After copying it over the one in the haccrypto folder, `mount_nandhac` started to work fine.

Just had to allow the macFUSE kernel extension and reboot, but now it's mounting fine. Thanks a lot! :)
