### ISSUE TITLE
No more mount to folder option in the 2.0 betas?

### ISSUE THREAD

**Issue by zacchi4k** [ihaveamac/ninfs#89]
Hi, sorry if this doesn't belong here, but I tried using the 2.0 betas and noticed I could no longer mount my DSi NAND to a folder and only to a drive on Windows, unlike the older versions. This makes it very difficult to edit the files on the NAND because tools like OFSMount can't see the virtual drive if it's mounted to a drive letter.
Is this feature planned to be reintroduced?

**Comment by ihaveamac** [comment]
The intention was for ninfs to have its own FAT32 mount so that it could handle the system partitions of DSi/3DS/Switch, removing the need for OSFMount and also having to explain how folder mounts work. But this might not happen for a while so I will probably re-add this to the gui when I have the motivation to work on this again. In the mean time, you can use the command line to mount to a directory again.

**Comment by ihaveamac** [comment]
53f98e27cd336ecb71d313cb73a8091669403ade re-adds directory mounts for nand types on Windows. Other types still use drive letters.
